src/ruby/meetings/config/routes.rb
Rails.application.routes.draw do

  resources :means_of_influences
  resources :entities
  Entity.types.each do |pi_type|
    resources (pi_type.underscore.downcase.pluralize.to_sym),controller: 'entities',type: pi_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (pi_type.underscore.downcase.pluralize.to_sym)
        resources :apidocs, only:[:index]
        resources :docs, only:[:index]
      end
    end
  end

  MeansOfInfluence.types.each do |pi_type|
    resources (pi_type.underscore.downcase.pluralize.to_sym),controller: 'means_of_influences',type: pi_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (pi_type.underscore.downcase.pluralize.to_sym)
      end
    end
  end

  InfluenceOfficePerson.types.each do |iop_type|
    resources (iop_type.underscore.downcase.pluralize.to_sym),controller: 'influence_office_person',type: iop_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (iop_type.underscore.downcase.pluralize.to_sym)
      end
    end
  end


  namespace :api do
    namespace :v1 do
      jsonapi_resources :source_files
    end
  end

  get '/swagger-docs' => redirect('/swagger/dist/index.html?url=/api/v1/apidocs')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
end

src/ruby/meetings/app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-dark.bg-inverse
  .navbar-header
    =link_to t(:home_page),root_path,class: 'navbar-brand',id: 'link-to-homepage'
  %ul.nav.navbar-nav
    %li.nav-item
      =link_to Person.model_name.human(count: 2).capitalize,people_path,class:'nav-link'
    %li.nav-item
      =link_to GovernmentOffice.model_name.human(count: 2).capitalize,government_offices_path,class:'nav-link'
    %li.nav-item
      =link_to Organisation.model_name.human(count: 2).capitalize,organisations_path,class:'nav-link'
    %li.nav-item
      =link_to Meeting.model_name.human(count: 2).capitalize,meetings_path,class:'nav-link'
    %li.nav-item
      =link_to Hospitality.model_name.human(count: 2).capitalize,hospitalities_path,class:'nav-link'
    %li.nav-item
      =link_to Gift.model_name.human(count: 2).capitalize,gifts_path,class:'nav-link'
    %li.nav-item
      =link_to Travel.model_name.human(count: 2).capitalize,travels_path,class:'nav-link'
    %li.nav-item.dropdown#docs
      =link_to '#',class: 'nav-link dropdown-toggle', 'data-toggle'=>'dropdown' do
        = t('documentation')
        %span.caret
      .dropdown-menu
        =link_to 'Api Docs',api_v1_docs_path,class: 'dropdown-item'
        =link_to 'Swagger Docs',swagger_docs_path,target: '_blank',class: 'dropdown-item'
  %ul.nav.navbar-inline.pull-xs-right
    %li.nav-item.dropdown#flags
      =link_to '#',class: 'nav-link dropdown-toggle', 'data-toggle'=>'dropdown' do
        = image_tag("#{extract_locale_key}.png")
        = t("countries.#{extract_locale_key}")
        %span.caret
      .dropdown-menu
        - I18n.available_locales.each do |locale_key|
          =link_to url_for_locale(locale_key),{id: "link_to_#{locale_key}",class: 'dropdown-item'} do
            = image_tag("#{locale_key}.png")
            = t("countries.#{locale_key}")

src/ruby/meetings/app/views/layouts/application.html.haml
!!! 5
%html{lang: I18n.locale,class: 'creative'}
  %head
    %meta{name:"viewport", content:"width=device-width, initial-scale=1"}
    %title
      -if content_for?(:title)
        = yield :title
      -else
        = t('application_name')
    = stylesheet_link_tag "application"
    = javascript_include_tag "application" , "data-turbolinks-track" => true 
    = yield :js
    = csrf_meta_tags 
  %body{id:controller.controller_name,class: 'container-fluid'}
    .container
      = render 'layouts/navbar'
    - if notice || alert
      .row
        %div{class: 'col-md-6 col-md-offset-3'}
          - if notice
            %div{class: 'alert alert-success', role: 'alert'}
              %p.notice= notice
          - if alert
            %div{class: 'alert alert-danger', role: 'alert'}
              %p.alert= alert
    %main.container
      -if content_for?(:content)
        = yield :content
      -else  
        = yield