src/ruby/meetings/config/routes.rb
Rails.application.routes.draw do

  resources :means_of_influences
  resources :entities
  Entity.types.each do |pi_type|
    resources (pi_type.underscore.downcase.pluralize.to_sym),controller: 'entities',type: pi_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (pi_type.underscore.downcase.pluralize.to_sym)
        resources :apidocs, only:[:index]
        resources :docs, only:[:index]
      end
    end
  end

  MeansOfInfluence.types.each do |pi_type|
    resources (pi_type.underscore.downcase.pluralize.to_sym),controller: 'means_of_influences',type: pi_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (pi_type.underscore.downcase.pluralize.to_sym)
      end
    end
  end

  InfluenceOfficePerson.types.each do |iop_type|
    resources (iop_type.underscore.downcase.pluralize.to_sym),controller: 'influence_office_person',type: iop_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (iop_type.underscore.downcase.pluralize.to_sym)
      end
    end
  end


  namespace :api do
    namespace :v1 do
      jsonapi_resources :source_files
    end
  end

  get '/swagger-docs' => redirect('/swagger/dist/index.html?url=/api/v1/apidocs')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
end

src/ruby/meetings/app/models/entity.rb
class Entity < ApplicationRecord
  def self.types
    %w(Person Organisation GovernmentOffice)
  end

  validates :name,presence: true

  self.types.each do |klass|
    scope klass.underscore.downcase.pluralize.to_sym,->{where(type: klass)}
  end

end

src/ruby/meetings/app/controllers/api/v1/entities_controller.rb
class Api::V1::EntitiesController < JSONAPI::ResourceController
end

src/ruby/meetings/app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_type
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = type_class.all.page params[:page]
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = type_class.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = type_class.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_type
    @type = type
  end

  def type
    params[:type] || "Entity"
  end

  def type_class
    @type_class = type.constantize
  end

  def set_entity
    @entity = type_class.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def entity_params
    params.require(type.underscore.to_sym).permit(:name, :wikipedia_entry)
  end
end

src/ruby/meetings/app/helpers/entities_helper.rb
module EntitiesHelper
end

src/ruby/meetings/app/views/entities/_form.html.haml
= form_for @entity do |f|
  - if @entity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entity.errors.count, "error")} prohibited this entity from being saved:"
      %ul
        - @entity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :wikipedia_entry
    = f.text_field :wikipedia_entry
  .field
    = f.label :type
    = f.text_field :type
  .actions
    = f.submit 'Save'

src/ruby/meetings/app/views/entities/edit.html.haml
%h1 Editing entity

= render 'form'

= link_to 'Show', @entity
\|
= link_to 'Back', entities_path

src/ruby/meetings/app/views/entities/index.html.haml
-content_for :title do
  = @type.pluralize

-content_for :content do
  .card
    .card-block
      %h1.card-title= @type_class.model_name.human(count: 2).capitalize
    .card-block
      %table.table.table-inverse.table-striped
        %thead
          %tr
            %th Name
            %th Wikipedia entry
            %th

        %tbody
          - @entities.each do |entity|
            %tr
              %td= entity.name
              %td= entity.wikipedia_entry
              %td= link_to 'Show', send("#{@type.underscore.downcase}_path",entity)

src/ruby/meetings/app/views/entities/new.html.haml
%h1 New entity

= render 'form'

= link_to 'Back', entities_path

src/ruby/meetings/app/views/entities/show.html.haml
.card
  .card-block
    %h1.card-title= @type_class.model_name.human(count: 1).capitalize
  .card-block
    %p
      %b Name:
      = @entity.name
    %p
      %b Wikipedia entry:
      = @entity.wikipedia_entry
    = link_to 'Back', send("#{@type.underscore.pluralize.downcase}_path")
  .card-block
    -if @entity.meetings.count > 0
      %table.table.table-inverse.table-striped
        %caption=Meeting.model_name.human(count: 2).capitalize
        %thead
          %tr
            %th{width: '10%'} Date
            %th Purpose
            %th Organisations
            %th

        %tbody
          - @entity.meetings.decorate.each do |meeting|
            %tr
              %td= meeting.date_string
              %td= meeting.purpose
              %td= meeting.organisation_side
              %td= link_to 'Show', meeting_path(meeting)

    -if @entity.travels.count > 0
      %table.table.table-inverse.table-striped
        %caption=Travel.model_name.human(count: 2).capitalize
        %thead
          %tr
            %th{width: '10%'} Date
            %th Purpose
            %th Organisations
            %th

        %tbody
          - @entity.travels.decorate.each do |travel|
            %tr
              %td= travel.date_string
              %td= travel.purpose
              %td= travel.organisation_side
              %td= link_to 'Show', travel_path(travel)

    -if @entity.hospitalities.count > 0
      %table.table.table-inverse.table-striped
        %caption=Hospitality.model_name.human(count: 2).capitalize
        %thead
          %tr
            %th{width: '10%'} Date
            %th Type of Hospitality 
            %th Organisations
            %th

        %tbody
          - @entity.hospitalities.decorate.each do |hospitality|
            %tr
              %td= hospitality.date_string
              %td= hospitality.type_of_hospitality
              %td= hospitality.organisation_side
              %td= link_to 'Show', hospitality_path(hospitality)
    -if @entity.gifts.count > 0
      %table.table.table-inverse.table-striped
        %caption=Gift.model_name.human(count: 2).capitalize
        %thead
          %tr
            %th{width: '10%'} Date
            %th Gift
            %th Value
            %th Organisations
            %th

        %tbody
          - @entity.gifts.decorate.each do |gift|
            %tr
              %td= gift.date_string
              %td= gift.gift
              %td= gift.value
              %td= gift.organisation_side
              %td= link_to 'Show', gift_path(gift)