src/ruby/meetings/config/routes.rb
Rails.application.routes.draw do

  resources :means_of_influences
  resources :entities
  Entity.types.each do |pi_type|
    resources (pi_type.underscore.downcase.pluralize.to_sym),controller: 'entities',type: pi_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (pi_type.underscore.downcase.pluralize.to_sym)
        resources :apidocs, only:[:index]
        resources :docs, only:[:index]
      end
    end
  end

  MeansOfInfluence.types.each do |pi_type|
    resources (pi_type.underscore.downcase.pluralize.to_sym),controller: 'means_of_influences',type: pi_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (pi_type.underscore.downcase.pluralize.to_sym)
      end
    end
  end

  InfluenceOfficePerson.types.each do |iop_type|
    resources (iop_type.underscore.downcase.pluralize.to_sym),controller: 'influence_office_person',type: iop_type
    namespace :api do
      namespace :v1 do
        jsonapi_resources (iop_type.underscore.downcase.pluralize.to_sym)
      end
    end
  end


  namespace :api do
    namespace :v1 do
      jsonapi_resources :source_files
    end
  end

  get '/swagger-docs' => redirect('/swagger/dist/index.html?url=/api/v1/apidocs')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
end

src/ruby/meetings/app/models/means_of_influence.rb
class MeansOfInfluence < ApplicationRecord
  def self.types
    %w(Meeting Hospitality Gift Travel)
  end
  validates :month, :year, :source_file_id, :source_file_line_number, presence: true
  has_many :influence_government_office_people
  has_many :influence_organisation_people
  has_many :organisations, through: :influence_organisation_people, source: 'organisation'
  has_many :organisation_people, through: :influence_organisation_people, source: 'person'
  has_many :government_people, through: :influence_government_office_people, source: 'person'
  has_many :government_offices, through: :influence_government_office_people, source: 'government_office'

  belongs_to :source_file

  self.types.each do |klass|
    scope klass.underscore.downcase.pluralize.to_sym,->{where(type: klass)}
  end

  default_scope -> { order(year: :asc,month: :asc) }

end

src/ruby/meetings/app/controllers/api/v1/means_of_influences_controller.rb
class Api::V1::MeansOfInfluencesController < JSONAPI::ResourceController
end

src/ruby/meetings/app/controllers/means_of_influences_controller.rb
class MeansOfInfluencesController < ApplicationController
  before_action :set_type
  before_action :set_means_of_influence, only: [:show, :edit, :update, :destroy]

  # GET /means_of_influences
  # GET /means_of_influences.json
  def index
    @means_of_influences = type_class.all
  end

  # GET /means_of_influences/1
  # GET /means_of_influences/1.json
  def show
  end

  # GET /means_of_influences/new
  def new
    @means_of_influence = type_class.new
  end

  # GET /means_of_influences/1/edit
  def edit
  end

  # POST /means_of_influences
  # POST /means_of_influences.json
  def create
    @means_of_influence = type_class.new(means_of_influence_params)

    respond_to do |format|
      if @means_of_influence.save
        format.html { redirect_to @means_of_influence, notice: 'Means of influence was successfully created.' }
        format.json { render :show, status: :created, location: @means_of_influence }
      else
        format.html { render :new }
        format.json { render json: @means_of_influence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /means_of_influences/1
  # PATCH/PUT /means_of_influences/1.json
  def update
    respond_to do |format|
      if @means_of_influence.update(means_of_influence_params)
        format.html { redirect_to @means_of_influence, notice: 'Means of influence was successfully updated.' }
        format.json { render :show, status: :ok, location: @means_of_influence }
      else
        format.html { render :edit }
        format.json { render json: @means_of_influence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /means_of_influences/1
  # DELETE /means_of_influences/1.json
  def destroy
    @means_of_influence.destroy
    respond_to do |format|
      format.html { redirect_to means_of_influences_url, notice: 'Means of influence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_type
    @type = type
  end

  def type
    params[:type] || "MeansOfInfluence"
  end

  def type_class
    @type_class = type.constantize
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_means_of_influence
    @means_of_influence = type_class.find(params[:id]).decorate
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def means_of_influence_params
    params.
      require(:means_of_influence).
      permit(:type, :day, :month, :year, :purpose, :type_of_hospitality,
             :gift, :value, :source_file_id, :source_file_line_number)
  end
end

src/ruby/meetings/app/helpers/means_of_influences_helper.rb
module MeansOfInfluencesHelper
end

src/ruby/meetings/app/views/means_of_influences/_form.html.haml
= form_for @means_of_influence do |f|
  - if @means_of_influence.errors.any?
    #error_explanation
      %h2= "#{pluralize(@means_of_influence.errors.count, "error")} prohibited this means_of_influence from being saved:"
      %ul
        - @means_of_influence.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :day
    = f.number_field :day
  .field
    = f.label :month
    = f.number_field :month
  .field
    = f.label :year
    = f.number_field :year
  .field
    = f.label :purpose
    = f.text_field :purpose
  .field
    = f.label :type_of_hospitality
    = f.text_field :type_of_hospitality
  .field
    = f.label :gift
    = f.text_field :gift
  .field
    = f.label :value
    = f.number_field :value
  .actions
    = f.submit 'Save'

src/ruby/meetings/app/views/means_of_influences/edit.html.haml
%h1 Editing means_of_influence

= render 'form'

= link_to 'Show', @means_of_influence
\|
= link_to 'Back', means_of_influences_path

src/ruby/meetings/app/views/means_of_influences/index.html.haml
-content_for :title do
  = @type.pluralize
-content_for :content do
  .card
    .card-block
      %h1.card-title= @type_class.model_name.human(count: 2).capitalize
    .card-block
      %table.table.table-inverse.table-striped
        %thead
          %tr
            %th{width: '10%'} Date
            -case @type
              -when 'Meeting','Travel'
                %th Purpose
              -when 'Hospitality'
                %th Type of hospitality
              -when 'Gift'
                %th Gift
                %th Value
            %th Department
            %th Organisation 
            %th
        %tbody
          - @means_of_influences.decorate.each do |means_of_influence|
            %tr
              %td= means_of_influence.date_string
              -case @type
                -when 'Meeting','Travel'
                  %td= means_of_influence.purpose
                -when 'Hospitality' 
                  %td= means_of_influence.type_of_hospitality
                -when 'Gift'
                  %td= means_of_influence.gift
                  %td= means_of_influence.value
              %td= means_of_influence.government_side
              %td= means_of_influence.organisation_side
              %td= link_to 'Show', send("#{@type.underscore.downcase}_path",means_of_influence)

src/ruby/meetings/app/views/means_of_influences/new.html.haml
%h1 New means_of_influence

= render 'form'

= link_to 'Back', means_of_influences_path

src/ruby/meetings/app/views/means_of_influences/show.html.haml
.card
  .card-block
    %h1.card-title= @type_class.model_name.human(count: 1).capitalize
  .card-block
    %p
      %b Date:
      = @means_of_influence.date_string
    -case @type
      -when 'Meeting','Travel'
        %p
          %b Purpose:
          = @means_of_influence.purpose
      -when 'Hospitality'
        %p
          %b Type of hospitality:
          = @means_of_influence.type_of_hospitality
      -when 'Gift'
        %p
          %b Gift:
          = @means_of_influence.gift
        %p
          %b Value:
          = @means_of_influence.value
    = link_to @type.pluralize, send("#{@type.underscore.downcase.pluralize}_path")
  .card-block
    %table.table.table-inverse.table-striped
      %caption Government Representation
      %thead
        %tr
          %th Name
          %th Office
      %tbody
        - @means_of_influence.influence_government_office_people.each do |igp|
          %tr
            %th= link_to igp.person.name, igp.person
            %th= link_to igp.government_office.name, igp.government_office
    %table.table.table-inverse.table-striped
      %caption Organisation Representation
      %thead
        %tr
          %th Organisation
      %tbody
        - @means_of_influence.influence_organisation_people.each do |iop|
          %tr
            %th= link_to  iop.organisation.name, iop.organisation